"""creation tables users capteurs mesures

Revision ID: 354bd64dccb3
Revises: 
Create Date: 2026-08-13 14:13:04.280333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354bd64dccb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)


    op.create_table('capteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=False),
    sa.Column('localisation', sa.String(length=150), nullable=True),
    sa.Column('seuil_min', sa.Float(), nullable=True),
    sa.Column('seuil_max', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capteurs_id'), 'capteurs', ['id'], unique=False)


    op.create_table('mesures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('capteur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capteur_id'], ['capteurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesures_horodatage'), 'mesures', ['horodatage'], unique=False)
    op.create_index(op.f('ix_mesures_id'), 'mesures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mesures_id'), table_name='mesures')
    op.drop_index(op.f('ix_mesures_horodatage'), table_name='mesures')
    op.drop_table('mesures')
    op.drop_index(op.f('ix_capteurs_id'), table_name='capteurs')
    op.drop_table('capteurs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    # ### end Alembic commands ###