# creation table alertes

# Revision ID: da6ab58ff7e1
# Revises: 354bd64dccb3
# Create Date: 2026-08-25 14:04:35.104014

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6ab58ff7e1'
down_revision: Union[str, Sequence[str], None] = '354bd64dccb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('valeur_mesuree', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('declenchee_le', sa.DateTime(), nullable=False),
    sa.Column('resolue_le', sa.DateTime(), nullable=True),
    sa.Column('capteur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capteur_id'], ['capteurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertes_declenchee_le'), 'alertes', ['declenchee_le'], unique=False)
    op.create_index(op.f('ix_alertes_id'), 'alertes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alertes_id'), table_name='alertes')
    op.drop_index(op.f('ix_alertes_declenchee_le'), table_name='alertes')
    op.drop_table('alertes')
    # ### end Alembic commands ###
